# Read the documentation before extending the defaults:
# https://docs.searxng.org/admin/settings/

use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - duckduckgo web
      - brave
      - bing
      - startpage
      - google

server:
  secret_key: "yTADTl8YdHQp0YiL2mXgnzg80pAIun9"
  image_proxy: true

search:
  formats:
    - html
    - json

outgoing:
  request_timeout: 8.0
  max_request_timeout: 12.0

engines:
  - name: google
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: duckduckgo web
    disabled: false
  - name: bing
    disabled: false
  - name: brave
    disabled: true
  - name: startpage
    disabled: false
